# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3caf4426337b99b65b9316d810d39f5d"
application_url = "https://seo-descriptions-ai-production.up.railway.app"
embedded = true
name = "SEOscribe"

[access_scopes]
scopes = "write_products,read_products"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks"


[auth]
redirect_urls = [ "https://seo-descriptions-ai-production.up.railway.app/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
